---

language: python
python:
 - "2.6"
 - "2.7"
before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq inkscape
script:
  - python make_machine.py dibond
  - python make_machine.py mendel
  - python make_machine.py sturdy
